# Generated by Django 5.0.6 on 2024-05-09 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_contact', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('value', models.CharField(choices=[('Fragile', 'Fragile'), ('Durable', 'Durable'), ('Perishable', 'Perishable')], max_length=10)),
                ('destination', models.CharField(choices=[('Mbale', 'Mbale'), ('Bukedea', 'Bukedea'), ('Kumi', 'Kumi'), ('Mukura', 'Mukura'), ('Soroti', 'Soroti'), ('Ngora', 'Ngora'), ('Kalaki', 'Kalaki'), ('Kaberamaido', 'Kaberamaido'), ('Ochero', 'Ochero'), ('Namasale', 'Namasale')], max_length=50)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_contact', models.CharField(max_length=15)),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.CharField(choices=[('9am', 'SINAI leaving at 9am'), ('11am', 'ZION leaving at 11am'), ('2pm', 'SINAI leaving at 2pm'), ('4pm', 'OLIVE leaving at 4pm'), ('6pm', 'JERICHO (SPECIFICALLY FOR CARGO) leaving at 6pm'), ('8pm', 'GALILEE leaving at 8pm'), ('10pm', 'JORDAN leaving at 10pm'), ('12am', 'CANNAN leaving at 12am'), ('2am', 'MOSES leaving at 2am'), ('4am', 'KAISARIA leaving at 4am'), ('6am', 'EXODUS leaving at 6am'), ('8am', 'REVELATION leaving at 8am'), ('10am', 'MARANATHA leaving at 10am'), ('12pm', 'SALVATION leaving at 12pm'), ('2pm', 'CASTA leaving at 2pm'), ('4pm', '695 leaving at 4pm')], max_length=50)),
                ('sender_email', models.EmailField(max_length=254)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='parcel_images/')),
                ('status', models.CharField(choices=[('Delayed', 'Delayed'), ('Arrived', 'Arrived'), ('Transporting', 'Transporting')], max_length=20)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
